### ISSUE TITLE
ov_secondary/camera_models opencv version problem

### ISSUE THREAD

**Issue by WoosikLee2510** [rpng/ov_secondary#1]
Hey, I had a problem while I try to build this project. The problem is coming from OpenCV version. One of my error, for instance, is 
```
‘CV_GRAY2RGB’ was not declared in this scope
```
which is a function of OpenCV version 2 while I'm using 3. I think the codes you copied from (maybe Vins fusion?) is using OpenCV functions that are deprecated.

**Comment by xiaocijun** [comment]
Add the header file #include<opencv2/imgproc/types_c.h> to the error file
