### ISSUE TITLE
Topic mismatch

### ISSUE THREAD

**Issue by qiaozhijian** [rpng/ov_secondary#2]
I run posegraph.launch, but it stopps at "[POSEGRAPH]: waiting for camera info topic...". I check the code and find open-vins doesn't publish these topic

**Comment by goldbattle** [comment]
OpenVINS publishes a series of topics under the `/ov_msckf/keyframe_*`. You can checkout [this launch file](https://github.com/rpng/ov_secondary/blob/master/loop_fusion/launch/posegraph.launch) for an example on how to run it. Note that we typically had to increase the number of extracted features to allow for good loop closure detection.

The main entry you will likely need to change is the image topic, which is specific to the dataset you are playing it on.
The other topics should publish by default with the latest master branch from the OpenVINS repo.
```
<remap from="/cam0/image_raw"                  to="/cam0/image_raw"/>
<remap from="/vins_estimator/extrinsic"        to="/ov_msckf/keyframe_extrinsic"/>
<remap from="/vins_estimator/keyframe_point"   to="/ov_msckf/keyframe_feats"/>
<remap from="/vins_estimator/keyframe_pose"    to="/ov_msckf/keyframe_pose"/>
<remap from="/vins_estimator/intrinsics"       to="/ov_msckf/keyframe_intrinsics"/>
```

**Comment by qiaozhijian** [comment]
I updated the master branch, and it works.  Thank you for maintaining open-vins!
