### ISSUE TITLE
ov_secondary does not work with  opencv 4.2.0

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/ov_secondary#5]
On trying to build the repo, I was unable to build it with opencv 4.2.0. I would like to know how to run this together with Openvins by just switching the opencv version to 3 ? Is there any alternative for this? merely changing the cmake text does 
not work.

Also, does this work only on 18.04 ubuntu?

**Comment by Aishkrish18** [comment]
CLosing this issue, since i made a docker to work with opencv 3 and using it to communicate with openvins noetic version.

**Comment by gianlucaparadiso** [comment]
Hi @Aishkrish18! I am facing the same issues. I have attempted a porting in ros 2 Humble, but it is taking me way too long to solve all the errors. Could you share your Dockerfile to run ov_secondary? 

Thanks!
